### ISSUE TITLE
Project Feedback!

### ISSUE THREAD

**Issue by Daphne-CPAdmin** [Subohi/Twitter_ios_#1]
It looks like the following features are not reflected on your GIF walkthrough: 

-  User stays logged in across restarts. (1pt)

Since the extension period is over, we will no longer regrade any resubmissions made after this date.

**Comment by Subohi** [comment]
Hey Daphne,

The gif was getting way too long therefore it didn't show up but I have
implemented it, it's in the code.

Best,
Subohi

**Comment by Daphne-CPAdmin** [comment]
Hi Subohi,

Could you record another GIF showing that part only and attach it to your
readme? You can have multiple gifs or gif per feature if you have to.
Thanks and let me know once that's done.

Have a wonderful weekend!

---

Daphne Jane Rendora
iOS/SE102 Operations
CodePath.org <http://codepath.org/>
daphne@codepath.org
